### PR TITLE
Add SC2207 Intro to Database Systems

### PR DESCRIPTION
**Pull request by majulahsingapuri**
# New Contribution

## Contribution

List of items added:

- SC2207 Content

## Checklist

Tick/delete where appropriate

### Docs

- [x] Added a unique id, slug, sidebar_position, title and description in metadata of the file
- [x] Internal links are written as relative file locations not URI
- [x] Added `index.md` page when writing entry for a new folder where necessary
- [x] Images have been uploaded into the appropriate folder in `./static/img/docs/` with a name describing the content of the image
- [x] All content has been written in an objective and factual tone

## Declaration

- [x] I hereby declare that all opinions expressed are my own.
- [x] I understand that any content deemed to be hurful, offensive, provocative or working in opposition to creating a wholesome and helpful community will be removed and could lead to my removal from the organisation.
- [x] I have read the [Contribution Instructions](http://www.github.com/NTU-DSAI/NTU-DSAI.github.io/blob/master/Contributing.md).

### CODE REVIEW

**Comment by majulahsingapuri** [comment]
Creating a PR on behalf of @STrikeNone. Thanks for the contribution! Could i trouble you to run the pre-commit hook for formatting and add a description and tag into the header component? You can see other files for an example.

**Comment by STrikeNone** [comment]
> Creating a PR on behalf of @STrikeNone. Thanks for the contribution! Could i trouble you to run the pre-commit hook for formatting and add a description and tag into the header component? You can see other files for an example.

Apologies, I will run the pre-commit after later after work!

**Comment by majulahsingapuri** [comment]
By right the hook is supposed to run automatically when new commits are added. For now I will merge it in and run the pre-commit manually

**Comment by STrikeNone** [comment]
Thanks for helping to run the pre-commit. So just to check, subsequent reviews will just be to create a new pull-request and then to commit with the relevant changes (pre-commit shld auto generate). I'll try to add some of the Y2 modules when I have more time!

**Comment by majulahsingapuri** [comment]
Yup that's right. The pre-commit will [fix any formatting errors](https://github.com/NTU-DSAI/NTU-DSAI.github.io/pull/18) that are there in the files. Do look at [Contributing.md](https://github.com/NTU-DSAI/NTU-DSAI.github.io/blob/master/Contributing.md) for the full instructions.

**Pull request merged**
